### ISSUE TITLE
MAP_OPTIONS and MARKER_OPTIONS don't have any effect in the admin

### ISSUE THREAD

**Issue by mykljohn** [oscarmcm/django-places#11]
Hey Oscar, Thanks for all the help.  Here's another :)

In my admin.py I set the properties for map size and zoom as follows, but they have no effect.
```
    def position_map(self, instance):
        if instance.location is not None:
            return '<img src="http://maps.googleapis.com/maps/api/staticmap?center=%(latitude)s,%(longitude)s&zoom=%(zoom)s&size=%(width)sx%(height)s&maptype=roadmap&markers=%(latitude)s,%(longitude)s&sensor=false&visual_refresh=true&scale=%(scale)s&key=%(key)s" width="%(width)s" height="%(height)s">' % {
                'latitude': instance.location.latitude,
                'longitude': instance.location.longitude,
                'key': getattr(settings, 'PLACES_MAPS_API_KEY'),
                'zoom': 17,
                'width': 75,
                'height': 75,
                'scale': 2
            }
    position_map.allow_tags = True
```

**Comment by oscarmcm** [comment]
Hi @mykljohn i think that it's not an issue with django-places. You can read the docs about [google staticmaps](https://developers.google.com/maps/documentation/static-maps/intro) and check how to set the zoom and map size.

**Comment by mykljohn** [comment]
OK, there's something with my config that maybe you can help me with.

When I first open my admin screen it displays like this:

![map1](https://cloud.githubusercontent.com/assets/11919990/25862189/d6ae25d6-34ac-11e7-891f-418415ee17a2.png)

When I enter an address and select it, it zooms like this:
![map2](https://cloud.githubusercontent.com/assets/11919990/25862220/ec5c0394-34ac-11e7-8d8c-1f546b7c675a.png)

After I save it then displays with the zoom like this:
![map3](https://cloud.githubusercontent.com/assets/11919990/25862251/08c82436-34ad-11e7-8031-f9d682347e02.png)

What I would like it to do is:
1.  If there is no location (new record) open to the city center.
2. If there is a location zoom to the street view (image 2 above).

Any idea how to do that here?

**Comment by oscarmcm** [comment]
@mykljohn I see now, MAP_OPTIONS and MARKER_OPTIONS are not being used in the Django admin edit/create form. I will fix it later, thanks for the report 👍

**Comment by mykljohn** [comment]
Actually better than opening to the city center would be to center on the users GEOIP location.  Cheers

**Comment by mykljohn** [comment]
Have you made any headway with this?

**Comment by oscarmcm** [comment]
@mykljohn I've working in this past week, hopefully to release this week
