### ISSUE TITLE
Multiple PlacesField() Objects declaration in one Model clones data from one Object to the other.

### ISSUE THREAD

**Issue by YashitM** [oscarmcm/django-places#14]
### DESCRIPTION
Assuming there are two objects declared in the models as:
```
source_location = PlacesField()
destination_location = PlacesField()
```
In the admin page, whenever the source location is selected, the same is selected for the destination location and vice versa.
After submission of the data and on checking the database, the Place Name is unique, but the coordinates for both the locations are the same.

Some more issues (with Images) are mentioned in this question here: 
https://stackoverflow.com/questions/47767106/how-do-i-define-multiple-objects-of-the-same-type-django-places-placesfield-obj?noredirect=1#comment82510925_47767106

* Django Version: 2.0
* Python Version: 3.6.3
* Operating System: Windows 10 Pro 64bit (Version: 1703)

**Comment by oscarmcm** [comment]
@YashitM thanks for the finding the bug, gonna fix it

**Comment by oscarmcm** [comment]
@YashitM Hi, this issue is now solved.
