### ISSUE TITLE
Cannot render map

### ISSUE THREAD

**Issue by mbambadev** [oscarmcm/django-places#15]
I have django place model form it not show me map in view.
The doc only indicate how to use it with admin.
Please how can i render django place in template to show me map

* Django Version: 1.11
* Python Version: 3.4

**Comment by oscarmcm** [comment]
@mbambadev just render the map?

**Comment by mbambadev** [comment]
oscarmcm: I have leave your app, i have seen that maybe it not work correct. You answer me now, it too late. When i read the doc no mention found to use it in standart django template. Yes just render the map.

**Comment by swatipuchd** [comment]
@oscarmcm can I remove map? I just need to show places. If yes, then how?

**Comment by oscarmcm** [comment]
Adding example in the README about how to use outside the Django Admin https://github.com/oscarmcm/django-places/commit/82ec7ad787467839bdd71359a1c729b38a2f7489
