### ISSUE TITLE
Empty Map in admin

### ISSUE THREAD

**Issue by shutterfire** [oscarmcm/django-places#16]
Added a PlaceField to a model and API-Key in project settings.
A map field is shown, but no map is included.
If something is entered in the Adress Field and enter is hit, the content of the field get's removed, nothing else changes

* Django Version: 2.0
* Python Version: 3.6

**Comment by andreyshipilov** [comment]
Same here. Django 1.11.6

**Comment by oscarmcm** [comment]
Hi @shutterfire @andreyshipilov this seems to be a problem with geocomplete, im working on removing it and create a new release.
