### ISSUE TITLE
Django 3 incompatibility 

### ISSUE THREAD

**Issue by ericvieira** [oscarmcm/django-places#26]
### DESCRIPTION
I try install Django-places, but Django 3 remove six API.

django.utils.six - Remove usage of this vendored library or switch to six.
**source:** https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis 

* Django Version: 3
* Python Version: 3.8.0

**Comment by oscarmcm** [comment]
Thanks, will take a look for a proper Django 3.0 compatibility.

**Comment by mstudi** [comment]
I have dealt with this before, the easiest way is to use the external six library and then there is a minor change to the import. Another option is to create a django2 and django3 version of this excellent mapping library, but that is more work.

**Comment by oscarmcm** [comment]
@mstudi thanks for the suggestion, I think im going to  create a new major release with support for only Django 3.0, in order to avoid a new dependency to this package.

**Comment by mstudi** [comment]
Looking forward to the new release. I previously used it in a Django 2.x project and will definitely upgrade once available. As far as I can tell, your library has been the best package out there for this sort of Django-Google Maps integration for a while now. 
Cheers.

**Comment by oscarmcm** [comment]
Version 4.0.0 is now live https://pypi.org/project/dj-places/4.0.0/ feel free to test, and reopen this issue if something is not working correctly, thanks for the help @mstudi @ericvieira .
