### ISSUE TITLE
Django 4.0 Deprecation warnings

### ISSUE THREAD

**Issue by andrewgy8** [oscarmcm/django-places#31]
### DESCRIPTION
Hey! Thanks for the great lib. 

I just installed 4.0.0 with Django 3.1.3. Everything works. Except Im seeing quite a few deprecation messages that should be fixed for compat with Django 4.0. 

### Trace
```
  /usr/local/lib/python3.7/site-packages/places/widgets.py:22: RemovedInDjango40Warning: django.utils.translation.ugettext_lazy() is deprecated in favor of django.utils.translation.gettext_lazy().
    'placeholder': _('Latitude'),
```

### STEPS
1. install django 3.1 with dj-places 4.0.0 
2. Create a model with a location
3. Run a test, and youll see the warning

### EXPECTED
No deprecation warnings

### REALITY
Deprecation warnings

* Django Version: 3.1.3
* Python Version: 3.7.9

**Comment by oscarmcm** [comment]
Thanks, will check and fix as soon as possible.

**Comment by andrewgy8** [comment]
Cool. If you want, I can take care of it.

**Comment by oscarmcm** [comment]
@andrewgy8 awesome, feel free to open a new PR for this.
