### ISSUE TITLE
CommandError: Unable to serialize database: 'PlacesField' object has no attribute '_get_val_from_obj'

### ISSUE THREAD

**Issue by ibrahimroshdy** [oscarmcm/django-places#33]
### DESCRIPTION
Issue happens when using django dumpdata command, it attempts to call a function where it does not exist when data is being serialized to json format. 

### Trace
Here is the stack trace.
```bash
CommandError: Unable to serialize database: 'PlacesField' object has no attribute '_get_val_from_obj'
Exception ignored in: <generator object cursor_iter at 0x11df48cf0>
Traceback (most recent call last):
  File "<project_path>/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1557, in cursor_iter
    cursor.close()
sqlite3.ProgrammingError: Cannot operate on a closed database.
```
### STEPS
1. Adding a PlacesField() in a model
2. Using ` python manage.py dumpdata  > data.json`
3. Error in data serialization 

python = "3.7.9"
Django = "2.2.16"
dj-places = "3.1.0"

### WHAT TO FIX 
- The issue is at [line 57](https://github.com/oscarmcm/django-places/blob/4de6ac614038238cff3185988773ff822abf3f80/places/fields.py#L57) in places/fields.py file where it is
```python
    def value_to_string(self, obj):
        value = self._get_val_from_obj(obj)
        return smart_text(value)
```

##### and it has to be 

```python
    def value_to_string(self, obj):
        value = self.value_from_object(obj)
        return smart_text(value)
```

The issue and solution are adapted from the same problem with django-multiselectfield [at this issue](https://github.com/goinnn/django-multiselectfield/issues/74)

#### A TEMP FIX
- Manually changing the code above in the venv field after package download

**Comment by oscarmcm** [comment]
Thanks @ibrahimroshdy will fix this soon.

**Comment by ibrahimroshdy** [comment]
Hello @oscarmcm,
i submitted a [#35 ](pull request) regarding this issue
