### ISSUE TITLE
Render only address (exclude coordinates lat/lon)

### ISSUE THREAD

**Issue by caioricciuti** [oscarmcm/django-places#34]
### DESCRIPTION
Hello, first of all thanks for your work!
I need to render the address in my HTML template, but when I refer {{ mymodel.places }} naturally all the info is rendered, I would like to know if it's possible to render only the main address, without latitude and longitude. I tried filtering with slice {{ mymodel.places|slice:":2" }} but I didn't get an satisfactory result.

### EXPECTED
" Juquehy, São Sebastião - SP, Brasil "

### REALITY
"Juquehy, São Sebastião - SP, Brasil, -23.7628574, -45.7307804"

* Django Version: 3.1.3
* Python Version:  3.8.5

**Comment by oscarmcm** [comment]
@caioricciuti Did you tried to access the data in your template with `{{ obj_instance.place_field.place }}`

```python
    >>> from myapp.models import ModelName
    >>> poi = ModelName.objects.get(id=1)
    >>> poi.position
    Place('Metrocentro, Managua, Nicaragua', 52.522906, 13.41156)
    >>> poi.position.place
    'Metrocentro, Managua, Nicaragua'
    >>> poi.position.latitude
    52.522906
    >>> poi.position.longitude
    13.41156
```

I think that should work, let me know if it doesnt.
