### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by andrewgy8** [oscarmcm/django-places#36]
### DESCRIPTION
Anyway we can do a new release? This is blocking an upgrade to Django 4.0 solved by #32

**Comment by oscarmcm** [comment]
Hey @andrewgy8 thanks!! I'll do a new release today and let you know

**Comment by oscarmcm** [comment]
Hey @andrewgy8 I just published a new version to PyPI and created a new release :)

- https://pypi.org/project/dj-places/5.0.0/
- https://github.com/oscarmcm/django-places/releases/tag/v5.0.0

**Comment by andrewgy8** [comment]
Gracias!
