### ISSUE TITLE
Problems with djplaces

### ISSUE THREAD

**Issue by mykljohn** [oscarmcm/django-places#6]
I have a few questions, but I'll start with save and reopen.
When I save the location field is stored in MySQL here:
**84 Washington St, Port Chester, NY 10573, USA, 41.0006469, -73.6706125**
Then when I reopen the record in Admin, it is loaded as:
**Place: Washington St, Port Chester, NY , USA
Latitude: 84         Longitude: 10573**

The second thing is I can't seem to figure out how to save UTF-8 data.  
When I enter : **Queretaro** and select **Santiago de Querétaro, Mexico**
the map appears correctly, but when I save I get:

> Request Method: 	POST
> Request URL: 	https://xxxxxx.pythonanywhere.com/admin/juego/juego/109/
> Django Version: 	1.8
> Exception Type: 	UnicodeEncodeError
> Exception Value: 	
> 
> 'ascii' codec can't encode character u'\xe9' in position 57: ordinal not in range(128)
> 
> Exception Location: 	/home/xxxxx/.virtualenvs/myvirtualenv/local/lib/python2.7/site-packages/places/fields.py in get_prep_value, line 55

I'm obviously missing something :)

Here's my model:
```
class Juego(models.Model):
     usuario = models.ForeignKey(User, related_name='propietario',
                                blank=True, null=True)
    titulo = models.CharField(max_length=50, db_index=True)
    categoria = models.ForeignKey(Categoria, related_name='categoria')
    descripcion = models.TextField(blank=True, null=True)
    imagen = models.ImageField(upload_to='media')
    location = PlacesField(blank=True)

```
And my Admin:
```
class JuegoAdmin(admin.ModelAdmin):
    list_display = ['titulo', 'slug', 'usuario', 'categoria',]
    prepopulated_fields = {'slug': ('titulo',)}

    def position_map(self, instance):
        if instance.location is not None:
            return '<img src="http://maps.googleapis.com/maps/api/staticmap?center=%(latitude)s,%(longitude)s&zoom=%(zoom)s&size=%(width)sx%(height)s&maptype=roadmap&markers=%(latitude)s,%(longitude)s&sensor=false&visual_refresh=true&scale=%(scale)s&key=%(key)s" width="%(width)s" height="%(height)s">' % {
                'latitude': instance.location.latitude,
                'longitude': instance.location.longitude,
                'key': getattr(settings, 'PLACES_MAPS_API_KEY'),
                'zoom': 15,
                'width': 100,
                'height': 100,
                'scale': 2
            }
    position_map.allow_tags = True
admin.site.register(Juego, JuegoAdmin)
```

* Django Version: 1.8
* Python Version: 2.7

**Comment by oscarmcm** [comment]
Hi @mykljohn, thanks for this amazing issue traceback. 

For the first thing:

> When I save the location field is stored in MySQL here:
84 Washington St, Port Chester, NY 10573, USA, 41.0006469, -73.6706125
Then when I reopen the record in Admin, it is loaded as:
Place: Washington St, Port Chester, NY , USA
Latitude: 84 Longitude: 10573

- It's a problem with kwargs position

For the second thing:

> 'ascii' codec can't encode character u'\xe9' in position 57: ordinal not in range(128)

- It's the common python2 encoding issue

I've already pushed a fix and created a [new version of djplaces](https://pypi.python.org/pypi/dj-places/1.1.2) feel free to reopen if the problem persist.

Kudos!! 🥇

**Comment by mykljohn** [comment]
Excellent, Thanks for the quick response.  Works great.
