### ISSUE TITLE
[Question] Location (Place) field size

### ISSUE THREAD

**Issue by mykljohn** [oscarmcm/django-places#7]
One last Question :)  How can I change the width of the location field?  Is there already existing css for it?  I've looked and can't seem to find it.  I'm using Grappelli and thought that was causing so I disabled it, but it didn't fix it.  Cheers, Mykl

**Comment by oscarmcm** [comment]
Hi @mykljohn you want to do something like this?
![image](https://cloud.githubusercontent.com/assets/2553459/25784761/d214ccd8-332f-11e7-9f53-1a3177c39498.png)

**Comment by mykljohn** [comment]
Yes exactly like that :)

**Comment by oscarmcm** [comment]
You could do something like this:

```css
#map_place input { width: 100%; }
```

As you can see the fields in the admin [widget template](https://github.com/oscarmcm/django-places/blob/master/places/templates/places/widgets/places.html#L6) have an id attribute. Also it's necessary to add your custom admin css, with something like this:

```python
class MyModelAdmin(admin.ModelAdmin):
    class Media:
        js = ('js/admin/my_own_admin.js',)    
        css = {
             'all': ('css/admin/my_own_admin.css',)
        }
```
I'm thinking if add a custom field class should be cool and usable, but i'm not sure at all. Let me know what you think. 😄

**Comment by mykljohn** [comment]
I hates css :)  couldn't I just add it into places.css?

**Comment by oscarmcm** [comment]
Nope, There is no way to do it 😞

**Comment by mykljohn** [comment]
Ok, I need some help.  Like I said I'm using Grappelli , I edited screen.css and added css for this but the change doesn't appear.  :(  Did I mention I hate css? :)  

In places.html line 6 there's a reference to {{ place.html }}.  Where does that come from? 
        <td colspan="3" id="map_place">{{ place.html }}</td>
I'm guessing I need to reference the css change in there, correct?

**Comment by oscarmcm** [comment]
Ok, so

```html
{{ place.html }}
```
Render this tag
```html
<input class="places" data-geo="formatted_address" id="id_location_0" name="location_0" type="text" placeholder="Introduce una ubicación" autocomplete="off">
```
As I say before, for affect this input, you need to do:

```css
#map_place input { width: 100%; }
```

Make sure that your css is loaded in the admin and your css selectors works

**Comment by mykljohn** [comment]
Ok, I'm sorry I'm confused.  Can't I just modify screen.css (the main css for Grappelli) and add "places" to it?
Here's Grappelli screen.css pertinent lines:

The style that's currently used:
```
input[type=text], input[type=password], input[type="number"], .vDateField, .vTimeField, .vIntegerField, .vPositiveSmallIntegerField, .vManyToManyRawIdAdminField, .vForeignKeyRawIdAdminField {
    width: 118px;
}
```
The style I would like to use:
```
input[type="url"], input[type="email"], input.vTextField, input.vURLField, input.vFileBrowseField, textarea, .vLargeTextField, .vXMLLargeTextField {
    width: 278px;
}
```
so couldn't I add input.places to this line like this:
```
input[type="url"], input[type="email"], input.vTextField, input.vURLField, input.vFileBrowseField, input.places, textarea, .vLargeTextField, .vXMLLargeTextField {
    width: 278px;
}
```

**Comment by mykljohn** [comment]
Crap!  That actually worked, but I had made the change in my collectstatic directory and not in the site-packages folder...not sure why, but I got it.  I added input[id=id_location_0] {width:682px} to the end of screen.css

**Comment by oscarmcm** [comment]
So In the end you could solve it?? you can edit your admin css (screen.css) just make sure that the selector used are working 😄

**Comment by mykljohn** [comment]
Yes I got it working, thanks
