### ISSUE TITLE
Kwargs problem

### ISSUE THREAD

**Issue by mykljohn** [oscarmcm/django-places#8]
Just to be thorough :)

I think this is the problem with the kwargs position, in forms.py, line 23 Location is undefined:

            kwargs['initial'] = Location(*kwargs['initial'].split(','))

**Comment by mykljohn** [comment]
I think I found this problem, the data is saved as a comma delimited field with the first part supposed to be the place, the 2nd the longitude and the 3rd the latitude, but the place has commas as well.
This is how the data was saved in MySQL: 
12 Washington Street, Port Chester, NY, United States, 41.00286010000001, -73.6690049

And more interesting, if I remove the leading "12" it works.

**Comment by oscarmcm** [comment]
Ohhh maybe the bug comes from [this regex](https://github.com/oscarmcm/django-places/blob/master/places/fields.py#L48), nice catch @mykljohn

**Comment by mykljohn** [comment]
I'm looking at the Google Places Address From, https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform

If you incorporated this, it would be an additional step to have all of the fields separated, Street Number, Address, City, State, Country

**Comment by oscarmcm** [comment]
Hi @mykljohn i've already pushed a fix when the data was saved is:

> 12 Washington Street, Port Chester, NY, United States, 41.00286010000001, -73.6690049

Feel free to reopen it or create a new issue.
